name: chatty
description: "A new app for Chat Real Time"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # for integrating firebase
  firebase_core: ^2.24.2

  #for handling firebase authentication
  firebase_auth: ^4.15.3

  #for handling google sign in
  google_sign_in: ^6.2.1

  #for accessing cloud firestore database
  cloud_firestore: ^4.13.6

  #for showing profile image
  cached_network_image: ^3.3.0

  #for uploading system of image
  image_picker: ^1.0.5

  #for firebase storage to upload file
  firebase_storage: ^11.5.6



  # for using cupertino icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: "^0.13.1"
#
#flutter_launcher_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "images/icon.png"
#  min_sdk_android: 21
#  remove_alpha_ios: true

  # for recommended coding practice
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  #for enabling material design
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
