// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIbuqelp47fVYVFC2bxha5ig0fE1ihBNU',
    appId: '1:482929881730:web:7124cd136ccfba20227a9b',
    messagingSenderId: '482929881730',
    projectId: 'chatty-real',
    authDomain: 'chatty-real.firebaseapp.com',
    storageBucket: 'chatty-real.appspot.com',
    measurementId: 'G-SWJRPWEJTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFUMQz6mXzK-QTiKFxfzYfORhm9duC22E',
    appId: '1:482929881730:android:80e51a0c0bcb8715227a9b',
    messagingSenderId: '482929881730',
    projectId: 'chatty-real',
    storageBucket: 'chatty-real.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfgdd2QTT-FQHA30U02Bw4HBDBhEnaxHg',
    appId: '1:482929881730:ios:76a3fa4cfde68cfc227a9b',
    messagingSenderId: '482929881730',
    projectId: 'chatty-real',
    storageBucket: 'chatty-real.appspot.com',
    androidClientId: '482929881730-fr8aak4plul8j9es4p02bgpcq6e3pdrj.apps.googleusercontent.com',
    iosClientId: '482929881730-g4qvpsjvncfri1gbc6d5i1npfori1mo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatty',
  );
}
